name: Generate Weekly Solana Report with GitHub Pages

on:
  schedule:
    # Run every Saturday at 00:00 UTC (09:00 JST)
    - cron: '0 0 * * 6'
  workflow_dispatch: # Allow manual triggering

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  generate-report:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      run: |
        cd poc
        npm install

    - name: Generate enhanced report with charts
      env:
        SOLANA_RPC_ENDPOINT: ${{ secrets.SOLANA_RPC_ENDPOINT }}
        WALLET_ADDRESSES: ${{ secrets.WALLET_ADDRESSES }}
        DAYS_TO_FETCH: 7
      run: |
        cd poc
        npm run start:enhanced

    - name: Generate GitHub Pages content
      run: |
        cd poc
        npm run deploy

    - name: Commit reports and pages
      env:
        GIT_USER_NAME: ${{ secrets.GIT_USER_NAME }}
        GIT_USER_EMAIL: ${{ secrets.GIT_USER_EMAIL }}
      run: |
        git config --local user.email "${GIT_USER_EMAIL:-github-actions[bot]@users.noreply.github.com}"
        git config --local user.name "${GIT_USER_NAME:-github-actions[bot]}"
        git add poc/reports/ docs/
        git diff --staged --quiet || (git commit -m "📊 Add weekly report for week $(date +%Y-W%V) with charts and pages" && git push)

  # GitHub Pages deployment is handled automatically when docs/ folder is updated
  # Configure Pages in Settings → Pages → Source: Deploy from branch (main, /docs)